[workspace]
members = [
    "src/icpedia_backend/directory_canister",
    "src/icpedia_backend/user_canister",
    "src/icpedia_backend/shared",
]

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.12"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
debug = false
strip = true